require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - bin/*

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - post
    - get
    - path
    - RSpec.configure

RSpec/VariableName:
  Exclude:
    - spec/requests/*
