default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fitness_app_development

test:
  <<: *default
  database: fitness_app_test

production:
  <<: *default
  database: fitness_app_production
